MovieShop-master/src/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

    

        public async Task<IActionResult> Genre(int id, int pageSize = 30, int pageNumber = 1)
        {
            var movies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            return View("PagedIndex", movies);
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieAsync(id);
            return View(movie);
        }
    }
}

MovieShop-master/src/MovieShopMVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent:ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }
    }
}

MovieShop-master/src/MovieShopMVC/Views/Shared/_Genres.cshtml
@using ApplicationCore.Contracts.Services
@inject IGenreService GenreService

@foreach (var genre in await GenreService.GetAllGenres())
{
    @*@Html.ActionLink(genre.Name, "Genre", "Movies", new { genreId = genre.Id }, new { @class = "dropdown-item" })*@

    <a asp-action="genre" asp-controller="Movies" class="dropdown-item" asp-route-id="@genre.Id"> @genre.Name</a>
}

MovieShop-master/src/MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Movie Shop</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header class="p-2 bg-dark bg-gradient text-white text-uppercase">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="navbar-brand d-flex align-items-center mb-2 mb-lg-0 text-white text-uppercase text-decoration-none">
                Movie Shop
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Genres
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @*
                        @await Component.InvokeAsync("Genres")
                    *@
                        @await Html.PartialAsync("_Genres")
                    </div>
                </li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
            </form>
            <partial name="_LoginPartial"/>

        </div>
    </div>

</header>
<div class="container-fluid mt-1">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    @*<div class="container">
        &copy; 2021 - MovieShop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>*@
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", false)
<script>
    //$('form').one('submit',
    //    function () {
    //        console.log($('form').valid());
    //        $(this).find('button[type="submit"]').attr('disabled', 'disabled')
    //            .append('  <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>');
    //    });
</script>
</body>
</html>

MovieShop-master/src/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.ResponseModels.MovieCardResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>